// tslint:disable
export interface Player
{
	rotowire_id: number;
	years_exp: number;
	position: string;
	sportradar_id: string;
	full_name: string;
	age: number;
	stats_id: number;
	depth_chart_order: 1;
	practice_participation: string;
	gsis_id: string;
	birth_country: string;
	hashtag: string;
	espn_id: number;
	injury_body_part: string;
	fantasy_positions: string[];
	yahoo_id: number;
	fantasy_data_id: number;
	injury_notes: string;
	search_last_name: string;
	search_first_name: string;
	height: string;
	college: string;
	player_id: string;
	birth_city: string;
	birth_state: string;
	weight: string;
	injury_start_date: Date;
	last_name: string;
	injury_status: string;
	sport: string;
	rotoworld_id: number;
	search_full_name: string;
	birth_date: Date;
	high_school: string;
	active: boolean;
	search_rank: number;
	number: number;
	practice_description: string;
	team: string;
	news_updated: number;
	depth_chart_position: string;
	status: string;
	first_name: string;
	actual_pos_rank: number;

}
